_target_: udons.models.shuffle_transformer_model.ShuffleTransformerModel

lr: 0.0001
weight_decay: 0.0000
nb_classes: "${datamodule: nb_classes}"
nb_patches: "${datamodule: nb_patches}"
nb_channels: "${datamodule: nb_channels}"
n_mels: "${datamodule: n_mels}"
patch_len: "${datamodule: patch_len}"
model_dim: 1024
depth: 3
heads: 3
mlp_dim: 512
pool: "cls"
dim_head: 64
dropout: 0.0
emb_dropout: 0.0
