name: hearvalidator on baselines

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
#        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: apt-get
      run: |
        sudo apt-get install -y libsndfile-dev
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install hearvalidator
    - name: Get model weights
      run: |
        wget https://github.com/neuralaudio/hear-baseline/raw/main/saved_models/naive_baseline.pt
        wget https://github.com/neuralaudio/hear-baseline/raw/main/saved_models/naive_baseline_tf.npy
        wget https://github.com/neuralaudio/hear-baseline/raw/main/saved_models/naive_baseline_keras.h5
    - name: Validate hearbaseline (torch)
      run: |
        hear-validator hearbaseline
        hear-validator hearbaseline --model ./naive_baseline.pt
    - name: Validate hearbaseline (tensorflow)
      run: |
        hear-validator hearbaseline.tf.naive
        hear-validator hearbaseline.tf.naive --model ./naive_baseline_tf.npy
    - name: Validate hearbaseline (keras)
      run: |
        hear-validator hearbaseline.keras.naive
        hear-validator hearbaseline.keras.naive --model ./naive_baseline_keras.h5
    - name: Validate hearbaseline.torchopenl3
      run: |
        hear-validator hearbaseline.torchopenl3
    - name: Validate hearbaseline.wav2vec2
      run: |
        hear-validator hearbaseline.wav2vec2
    - name: Validate hearbaseline.vggish
      run: |
        hear-validator hearbaseline.vggish
    - name: Validate hearbaseline.vqt
      run: |
        hear-validator hearbaseline.vqt
    - name: Validate hearbaseline.torchcrepe
      run: |
        hear-validator hearbaseline.torchcrepe
