# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "hear-jigsaw"
  name: ${name}
  save_dir: "."
  offline: True # set True to store all logs only locally
  id: null # pass correct id to resume experiment!
  # entity: ""  # set to name of your wandb team or just remove it
  log_model: False
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
